// 你没有定义任何构造函数，但编译器会生成：
// 1. 默认构造函数 AutoGenerated()
// 2. 拷贝构造函数 AutoGenerated(const AutoGenerated&)
// 3. 赋值运算符 AutoGenerated& operator=(const AutoGenerated&)
// 4. 析构函数 ~AutoGenerated()



#include <iostream>
#include <cstring>

class SafePerson {
public:
    int age;
    char * name;
    SafePerson(const int age, const char * name) {
        this->age = age;
        //预留'\0'
        this->name = new char[strlen(name) + 1];
        strcpy(this->name, name);
        std::cout << this->name << "被构造成功\n";
    }
    ~SafePerson() {
        std::cout << this->name << "被销毁\n";
        delete[] this->name;
    }

    //やりますね(赞赏), 十分甚至是九分的好用啊. 直接报错
    //error: use of deleted function ‘SafePerson::SafePerson(const SafePerson&)’
    //error: use of deleted function ‘SafePerson::SafePerson(const SafePerson&)’
    SafePerson(const SafePerson &) = delete;                //防止创建时构造函数和赋值
    SafePerson & operator=(const SafePerson &) = delete;    //防止直接赋值

};

int main(void) {
    SafePerson sp1(24, "田所浩二");
    // SafePerson sp2(sp1);
    // SafePerson sp3 = sp1;
    SafePerson sp4(24, "sasagi");
    // sp4 = sp1;

    return 0;
}

// #include <iostream>

// class Person {
// public:
//     int age;
//     //如果不使用指针
//     char name[64];
//     Person(const int age, const char * n) {
//         this->age = age;
//         snprintf(this->name, sizeof this->name, n);
//         std::cout << name << "创建成功\n";
//     }
//     ~Person() {
//         std::cout << name << "销毁成功\n";
//     }
// };

// int main(void) {
//     Person p1(20, "张三");
//     Person p2(p1);
//     std::cout << "p2.name" << p2.name << "\n";
//     std::cout << "p1.name" << p1.name << "\n";

//     /**
//      * Breakpoint 1, main () at Test.cpp:19
//         19          Person p1(20, "张三");
//         (gdb) n
//         张三创建成功
//         20          Person p2(p1);
//         (gdb) p p1
//         $1 = {age = 20, 
//         name = "张三\000\367\377\177\000\000\b\037\350\367\377\177\000\000\000 \001\000\000\000\000\000\000 \001\000\000\000\000\000X\324\377\377\377\177\000\000h\324\377\377\377\177\000\000X\n\347\367\377\177\000\000\000\000\000"}
//         (gdb) p p2
//         $2 = {age = -1819111024, 
//         name = "\224\225\226\227 \033\277\367\377\177\000\000\020 \001\000\000\000\000\000\300\032\277\367\377\177\000\000\000\000\000\000\000\000\000\000X\n\347\367\377\177\000\000\000\000\000\000\000\000\000\000~֪\367\377\177\000\000\000 \001"}
//         (gdb) n
//         22          return 0;
//         (gdb) p p1
//         $3 = {age = 20, 
//         name = "张三\000\367\377\177\000\000\b\037\350\367\377\177\000\000\000 \001\000\000\000\000\000\000 \001\000\000\000\000\000X\324\377\377\377\177\000\000h\324\377\377\377\177\000\000X\n\347\367\377\177\000\000\000\000\000"}
//         (gdb) p p2
//         $4 = {age = 20, 
//         name = "张三\000\367\377\177\000\000\b\037\350\367\377\177\000\000\000 \001\000\000\000\000\000\000 \001\000\000\000\000\000X\324\377\377\377\177\000\000h\324\377\377\377\177\000\000X\n\347\367\377\177\000\000\000\000\000"}
//         (gdb) p p2->name
//         $5 = "张三\000\367\377\177\000\000\b\037\350\367\377\177\000\000\000 \001\000\000\000\000\000\000 \001\000\000\000\000\000X\324\377\377\377\177\000\000h\324\377\377\377\177\000\000X\n\347\367\377\177\000\000\000\000\000"
//         (gdb) p &p2->name
//         $6 = (char (*)[64]) 0x7fffffffd294
//         (gdb) p &p1->name
//         $7 = (char (*)[64]) 0x7fffffffd2e4
//         自动管理内在的不用怕, 手动管理内在的慎用!
//      */

//     return 0;
// } 

// #include <iostream>
// #include <cstring>
// using namespace std;

// // 一个简单的类
// //在构造函数中分配空间, 在析构函数中销毁空间
// class Person {
// public:
//     int age;
//     char* name;

//     Person(int a, const char* n) {
//         age = a;
//         name = new char[strlen(n) + 1];  // 动态分配内存
//         strcpy(name, n);
//         cout << "构造函数：" << name << " 创建" << endl;
//     }

//     ~Person() {
//         cout << "析构函数：" << (name ? name : "无名") << " 销毁" << endl;
//         delete[] name;  // 释放内存
//     }
// };

// int main() {
//     Person p1(20, "张三");  // 调用构造函数

//     Person p2 = p1;  // 这里发生了什么？
//     // Person p3(p1);   //这又什么鬼?
//     /**
//      *  构造函数：张三 创建
//         析构函数：张三 销毁
//         析构函数：���\ 销毁
//         free(): double free detected in tcache 2
//         Aborted                    (core dumped) ./a.out
//         // 编译器自动生成的拷贝构造函数是这样的：
//         Person(const Person& other) {
//             this->age = other.age;  // 复制age
//             this->name = other.name;  // 复制指针！不是复制字符串！
//         }

//         Breakpoint 1, main () at Test.cpp:26
//         26          Person p1(20, "张三");  // 调用构造函数
//         (gdb) 
//         (gdb) n
//         构造函数：张三 创建
//         29          Person p3(p1);   //这又什么鬼?
//         (gdb) n
//         43          return 0;
//         (gdb) p &p1
//         $1 = (Person *) 0x7fffffffd320
//         (gdb) p &p3
//         $2 = (Person *) 0x7fffffffd310
//         (gdb) p &p3->
//         age      name     ~Person  
//         (gdb) p &p3->age 
//         $3 = (int *) 0x7fffffffd310
//         (gdb) p &p1->age
//         $4 = (int *) 0x7fffffffd320
//         (gdb) p &p1->name 
//         $5 = (char **) 0x7fffffffd328
//         (gdb) p &p3->name 
//         $6 = (char **) 0x7fffffffd318
//         (gdb) p p3->name 
//         $7 = 0x55555556b320 "张三"
//         (gdb) p p1->name 
//         $8 = 0x55555556b320 "张三"


//         Breakpoint 1, main () at Test.cpp:26
//         26          Person p1(20, "张三");  // 调用构造函数
//         (gdb) n
//         构造函数：张三 创建
//         28          Person p2 = p1;  // 这里发生了什么？
//         (gdb) n
//         70          return 0;
//         (gdb) p p1
//         $1 = {age = 20, name = 0x55555556b320 "张三"}
//         (gdb) p p2
//         $2 = {age = 20, name = 0x55555556b320 "张三"}

//         如果是指针变量的话, 第一次销毁没问题, 第二次销毁时, 由于资源已经被销毁, 直接被判定为非法访问, 造成段错误
//      */

//     return 0;
// }




















//#include <stdio.h>
//#include <unistd.h>
//#include <pthread.h>
//
//void * start_routine(void * args) {
//    printf("I am a new thread\n");
//    sleep(1);
//	return nullptr;
//}
//
//int main(void) {
//    pthread_t tid;
//    pthread_create(&tid, NULL, &start_routine, NULL);
//    pthread_join(tid, NULL);
//
//    return 0;
//}
